#!/usr/bin/env bash

# Function to display information about a subdomain
display_info() {
   local subdomain="$1"
   local username="$2"
   local ip="$3"
   local state="$4"
   echo "$subdomain\t$username\t$ip\t$state"
}

domain="$1"

# If no subdomain argument provided, list information for all subdomains
if [ $# -eq 1 ]; then
   display_info "5762-web-01" "ubuntu" "52.91.242.136" "running"
   display_info "5762-web-02" "ubuntu" "18.207.144.212" "running"
   display_info "5762-lb-01" "ubuntu" "18.234.81.139" "running"
else
   echo "Usage: $0 domain"
fi

